version: '3.7'

services:
    backend:
        build: .\Backend_API\simple-api\simple-api-student 
        container_name: simple2
        networks:
        - app-network
        depends_on:
        - database

    database:
        build: .\Database
        container_name: mydb
        networks:
        - app-network

    httpd:
        build: .\Backend_API\simple-api\simple-api-student-front
        ports: 
        - "8081:80"
        networks:
        - app-network
        depends_on:
        - backend

networks:
    app-network: