FROM eclipse-temurin:17-jdk-alpine
# Build Main.java ith JDK
# TODO : in next steps (not now)

FROM eclipse-temurin:17-jre-alpine
# Copy resource from previous stage
COPY --from=0 /usr/src/Main.class .
# Run java code with the JRE
# TODO : in next steps (not now)