name: CI devops 2023
on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test with Maven
        run: mvn -f Backend_API/simpleapi/src/pom.xml clean install
